- name: Setup SDN Infrastructure (Faucet + Prometheus + cAdvisor)
  hosts: sdn-lab
  become: yes

  vars:
    faucet_conf_dir: "/etc/faucet"
    prom_conf_dir: "/etc/prometheus"

  tasks:
  - name: Update apt and install system dependencies
    apt:
      name:
        - help2man
        - apt-transport-https
        - ca-certificates
        - net-tools # для mininet
        - curl
        - gnupg
        - software-properties-common
        - python3-pip
        - openvswitch-switch
        - git
      state: present
      update_cache: yes

  - name: Add GPG keys
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repository to apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker engine and plugins
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: docker
      state: present

  - name: Adding ansible_mgr to docker group
    user:
      name: ansible_mgr
      groups: docker
      append: yes

  - name: Create config directories
    file:
      path: "{{ item }}"
      state: directory
      mode: '0777'
    loop:
      - "{{ faucet_conf_dir }}"
      - "{{ prom_conf_dir }}"

  - name: Deploy Faucet config
    template:
      src: templates/faucet.yaml.j2
      dest: "{{ faucet_conf_dir }}/faucet.yaml"

  - name: Deploy Prometheus config
    template:
      src: "templates/{{ item }}.yml.j2"
      dest: "{{ prom_conf_dir }}/{{ item }}.yml"
    loop:
      - "prometheus"
      - "alert_rules"

  - name: Run Faucet Controller
    docker_container:
      name: faucet
      image: faucet/faucet
      state: started
      restart_policy: always
      network_mode: host
      volumes:
        - "{{ faucet_conf_dir }}:/etc/faucet"

  - name: Run cAdvisor for container monitoring
    community.docker.docker_container:
      name: cadvisor
      image: gcr.io/cadvisor/cadvisor:v0.47.0
      state: started
      restart_policy: always
      privileged: true
      published_ports:
        - "8081:8080"
      devices:
        - "/dev/kmsg:/dev/kmsg"
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:ro"
        - "/sys:/sys:ro"
        - "/var/lib/docker/:/var/lib/docker:ro"
        - "/dev/disk/:/dev/disk:ro"

  - name: Run Prometheus
    docker_container:
      name: prometheus
      image: prom/prometheus
      state: started
      restart_policy: always
      network_mode: host
      user: "0:00"
      volumes:
        - "{{ prom_conf_dir }}:/etc/prometheus"
        - "prometheus_data:/prometheus"
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"


  - name: Clone Containernet repo
    git:
      repo: 'https://github.com/containernet/containernet.git'
      dest: /opt/containernet
      version: master

  - name: Allow break-system-packages globaly for pip
    file:
      path: ~/.config/pip
      state: directory

  - name: Set pip global break-system-packages
    copy:
      dest: ~/.config/pip/pip.conf
      content: |
        [global]
        break-system-packages = true

  - name: Install Containernet
    command:
      cmd: make install
      chdir: /opt/containernet
    register: install_result
    changed_when: "'Installing' in install_result.stdout"

  - name: Verify installation
    command: mn --version
    register: mn_version
  - debug:
      msg: "Mininet/Containernet version: {{ mn_version.stdout }}"

  - name: Copying balancer
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.group | default('root') }}"
      mode: "{{ item.mode | default('0644') }}"
    loop:
      - src: Balancer/sdn-balancer
        dest: /usr/local/bin/sdn-balancer
        mode: '0755'
        owner: root
        group: root

      - src: Balancer/faucet.yaml.tmpl
        dest: /etc/faucet/faucet.yaml.tmpl
        mode: '0644'
  
  - name: Create Systemd Unit
    ansible.builtin.copy:
      dest: /etc/systemd/system/sdn-balancer.service
      owner: root
      group: root
      mode: '0644'
      content: |
        [Unit]
        Description=SDN Traffic Load Balancer Agent
        After=network.target

        [Service]
        Type=simple
        ExecStart=/usr/local/bin/sdn-balancer
        Restart=always
        RestartSec=5
        User=root
        WorkingDirectory=/usr/local/bin

        [Install]
        WantedBy=multi-user.target
        
  - name: Reload Systemd, enable and start balancer service
    ansible.builtin.systemd:
      name: sdn-balancer
      state: restarted
      daemon_reload: true
      enabled: true