- name: Setup SDN Infrastructure (Faucet + Prometheus)
  hosts: sdn-lab
  become: yes

  vars:
    faucet_conf_dir: "/etc/faucet"
    prom_conf_dir: "/etc/prometheus"

  tasks:
  - name: Update apt and install system dependencies
    apt:
      name:
        - help2man
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
        - python3-pip
        - openvswitch-switch
        - git
      state: present
      update_cache: yes

  - name: Add GPG keys
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repository to apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker engine and plugins
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: docker
      state: present

  - name: Adding ansible_mgr to docker group
    user:
      name: ansible_mgr
      groups: docker
      append: yes

  - name: Create config directories
    file:
      path: "{{ item }}"
      state: directory
      mode: '0777'
    loop:
      - "{{ faucet_conf_dir }}"
      - "{{ prom_conf_dir }}"

  - name: Deploy Faucet config
    template:
      src: templates/faucet.yaml.j2
      dest: "{{ faucet_conf_dir }}/faucet.yaml"

  - name: Deploy Prometheus config
    template:
      src: templates/prometheus.yml.j2
      dest: "{{ prom_conf_dir }}/prometheus.yml"

  - name: Run Faucet Controller
    docker_container:
      name: faucet
      image: faucet/faucet
      state: started
      restart_policy: always
      network_mode: host
      volumes:
        - "{{ faucet_conf_dir }}:/etc/faucet"

  - name: Run Prometheus
    docker_container:
      name: prometheus
      image: prom/prometheus
      state: started
      restart_policy: always
      network_mode: host
      user: "0:00"
      volumes:
        - "{{ prom_conf_dir }}:/etc/prometheus"
        - "prometheus_data:/prometheus"
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"


  - name: Clone Containernet repo
    git:
      repo: 'https://github.com/containernet/containernet.git'
      dest: /opt/containernet
      version: master

  - name: Install Containernet
    command:
      cmd: make install
      chdir: /opt/containernet
    register: install_result
    changed_when: "'Installing' in install_result.stdout"

  - name: Verify installation
    command: mn --version
    register: mn_version
  - debug:
      msg: "Mininet/Containernet version: {{ mn_version.stdout }}"
